language: go
go:
- '1.9'
go_import_path: github.com/golang/dep
before_script:
- GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
- go get github.com/golang/lint/golint
- go get honnef.co/go/tools/cmd/megacheck
- go get github.com/fzipp/gocyclo
script:
- test -z $(gofmt -s -l $GO_FILES)
- go test -v -race ./...
- go vet ./...
- megacheck ./...
- gocyclo -over 19 $GO_FILES
deploy:
  provider: heroku
  api_key:
    secure: Yj0s9ad9qXzoNukF0KZNop0NWYdOsEHTXIVvdpFaVPloBFr4Xli3MnZDfKEf0olyb+Eenttt/Dn9z/1tesQGFJHmI0pXe6QaHDwGS0Ve1A1U3/2FpiYQANLiyovX2UIyB2GkcbhBmspXkjXE71KRksxmq8inwWMG1FU/kBHRbD4RqURPWZ8Zw2sP4swd7+o0QAUdqL1YcAqalVGuAK+ZakSlpS8yoPPj8BDeB/n6Otr2XHoh0WLGcMzN9cfdTg/zIo8Ahaqnu5g4Q8i3Lw+o1COtIW+DzZ1/LsPooIgzVTEzRfnpOKF2f34AyBS22EQWSK8DUv8UcFU2qgXIPI7Yabldbcg7lu3Wkmez90uwbc2HjgVv/1fOxioEFYYeOTnvCrgeQLTPi4JrIdqayRrMLYVL8/FrNUy1DZXfYIl5vSadhyQG7yy8I0qsALNbljIew0GH3HJObs7iu61VG2KKnrvkxwAiAET+6uPXEzr/s/G6VAUryAhBjjJ114+1EuZTsa/f/m38wNhWXzala2Zx/4hQFcJjhdact6U3CeslFfpUrkks5J1Hse7zzcIf1yJXDZ/u8GwN23l2FBg20Yf5I0s46CpObPoc+qMGqzPys/xj7Kpg0gRJlRYdZFxf3jRlniKJHFCzglmu66xMg2w4S7+4tQ4W2aPpL9v6cLjwk/E=
  app: polar-waters-49054
  on:
    repo: aliakseimaniuk/opendata-alexa
